com:
    pgoogol:
        searchservice:
            criteria-config:
                type: ELASTICSEARCH
                index-name: dictionary-config
                #type: FILE
                file: C:/log/config.json
                #file: /home/pgogol/config.json
                #index-name: xyz-dictionary

spring:
    elasticsearch:
        uris: ${ELK_REST_URIS:localhost:9200}
        username: ${ELK_USERNAME:}
        password: ${ELK_PASSWORD:}
        ssl_enabled: ${ELK_SSL_ENABLED:false}


logging:
    file:
        name: /tmp/logstash/log.log
    level:
        com:
            pgoogol:
                search-service: ${LOG_LEVEL_ROOT:DEBUG}
server:
    port: 8083